### ISSUE TITLE
AssertionError: WebSocket client does not request for the subprotocol graphql-ws!

### ISSUE THREAD

**Issue by AhmedSalam22** [datadvance/DjangoChannelsGraphqlWs#116]
`2023-12-03 16:44:41,352 daphne.server ERROR    Exception inside application: WebSocket client does not request 
for the subprotocol graphql-ws!
Traceback (most recent call last):
  File "C:\Users\admin\wwork\env\lib\site-packages\channels\routing.py", line 62, in __call__
    return await application(scope, receive, send)
  File "C:\Users\admin\wwork\env\lib\site-packages\channels\security\websocket.py", line 37, in __call__       
    return await self.application(scope, receive, send)
  File "C:\Users\admin\wwork\env\lib\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\admin\wwork\env\lib\site-packages\channels\sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\admin\wwork\env\lib\site-packages\channels\auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\admin\wwork\env\lib\site-packages\channels\middleware.py", line 24, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\admin\wwork\env\lib\site-packages\channels\routing.py", line 116, in __call__
    return await application(
  File "C:\Users\admin\wwork\env\lib\site-packages\channels\consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "C:\Users\admin\wwork\env\lib\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "C:\Users\admin\wwork\env\lib\site-packages\channels\utils.py", line 50, in await_many_dispatch
    await dispatch(result)
  File "C:\Users\admin\wwork\env\lib\site-packages\channels\consumer.py", line 73, in dispatch
    await handler(message)
  File "C:\Users\admin\wwork\env\lib\site-packages\channels\generic\websocket.py", line 173, in websocket_connect
    await self.connect()
  File "C:\Users\admin\wwork\env\lib\site-packages\channels_graphql_ws\graphql_ws_consumer.py", line 252, in connect`

**Comment by mn-48** [comment]
I have fetch the same error.
