### ISSUE TITLE
'AsgiRequest' object has no attribute 'register'

### ISSUE THREAD

**Issue by rigelk** [datadvance/DjangoChannelsGraphqlWs#14]
Hello,

After following the installation instructions, and using the example in the README with `django==2.2.1` and `django-channels-graphql-ws==0.2.0` on Python 3.7.3, when making any subscription operation:

```js
subscription {
  mySubscription {event}
}
```

```json
{
  "errors": [
    {
      "message": "'AsgiRequest' object has no attribute 'register'"
    }
  ],
  "data": null
}
```

Traceback:

```
Traceback (most recent call last):
  File "/.cache/pypoetry/virtualenvs/WcnE4_vK-py3.7/lib/python3.7/site-packages/graphql/execution/executor.py", line 447, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/.cache/pypoetry/virtualenvs/WcnE4_vK-py3.7/lib/python3.7/site-packages/graphql/execution/executors/sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "/.cache/pypoetry/virtualenvs/WcnE4_vK-py3.7/lib/python3.7/site-packages/graphene_django/debug/middleware.py", line 56, in resolve
    promise = next(root, info, **args)
  File "/***.py", line 86, in resolve
    result = next(root, info, **args)
  File "/***.py", line 37, in resolve
    return next(root, info, **args)
  File "/***.py", line 8, in resolve
    return result.get()
  File "/.cache/pypoetry/virtualenvs/WcnE4_vK-py3.7/lib/python3.7/site-packages/promise/promise.py", line 510, in get
    return self._target_settled_value(_raise=True)
  File "/.cache/pypoetry/virtualenvs/WcnE4_vK-py3.7/lib/python3.7/site-packages/promise/promise.py", line 514, in _target_settled_value
    return self._target()._settled_value(_raise)
  File "/.cache/pypoetry/virtualenvs/WcnE4_vK-py3.7/lib/python3.7/site-packages/promise/promise.py", line 224, in _settled_value
    reraise(type(raise_val), raise_val, self._traceback)
  File "/.cache/pypoetry/virtualenvs/WcnE4_vK-py3.7/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/.cache/pypoetry/virtualenvs/WcnE4_vK-py3.7/lib/python3.7/site-packages/promise/promise.py", line 487, in _resolve_from_executor
    executor(resolve, reject)
  File "/.cache/pypoetry/virtualenvs/WcnE4_vK-py3.7/lib/python3.7/site-packages/promise/promise.py", line 754, in executor
    return resolve(f(*args, **kwargs))
  File "/.cache/pypoetry/virtualenvs/WcnE4_vK-py3.7/lib/python3.7/site-packages/graphql/execution/middleware.py", line 76, in make_it_promise
    return next(*args, **kwargs)
  File "/.cache/pypoetry/virtualenvs/WcnE4_vK-py3.7/lib/python3.7/site-packages/channels_graphql_ws/graphql_ws.py", line 425, in _subscribe
    register = info.context.register
AttributeError: 'AsgiRequest' object has no attribute 'register'
```

While I can see where the 'register' attribute is needed: https://github.com/datadvance/DjangoChannelsGraphqlWs/blob/master/channels_graphql_ws/graphql_ws.py#L425, I can't see what could have caused it to be deleted from the context before going through `Subscription._subscribe`.

Do you have any idea what could lead to that situtation, and how to fix it?

**Comment by prokher** [comment]
@rigelk Thanks for reporting. Actually, it is not clear why the `info.context` is an instance of `AsgiRequest`. It is expected to be an `types.SimpleNamespace` instance initialized [here](https://github.com/datadvance/DjangoChannelsGraphqlWs/blob/master/channels_graphql_ws/graphql_ws.py#L1000). We will try to reproduce.

**Comment by hozblok** [comment]
Hey @rigelk ,

`AsgiRequest` is used in `channels.http.AsgiHandler`. If a `http` argument is not provided in [channels.routing.ProtocolTypeRouter](https://channels.readthedocs.io/en/latest/topics/routing.html#protocoltyperouter), it will default to the Django view system’s ASGI interface, `channels.http.AsgiHandler`.

So `AsgiHandler` is done specifically to work with ordinary normal Django views by default. In our example we don't provide `http`, we provide `websocket` argument for websocket connections:

```
application = channels.routing.ProtocolTypeRouter(
    {
        "websocket": channels.routing.URLRouter(
            [django.urls.path("graphql/", MyGraphqlWsConsumer)]
        )
    }
)
```
In this way our `GraphqlWsConsumer` from example does not use `AsgiRequest` and `AsgiHandler` for HTTP, because [AsyncJsonWebsocketConsumer](https://channels.readthedocs.io/en/latest/topics/consumers.html#asyncjsonwebsocketconsumer) doesn't do that. The only HTTP path (after which `AsgiRequest` will be created) in our example is the path to `graphiql`, but it is not connected to `GraphqlWsConsumer`:

```
urlpatterns = [django.urls.path("", graphiql)]
```

Could you show how you configure `ProtocolTypeRouter` and `urlpatterns`? What kind of requests do you send to the server via HTTP? This could help reproduce this problem.

**Comment by Thibaut-Fatus** [comment]
I've encountered the same issue when trying to start subscriptions over HTTP instead of WS - the protocol I use in my `ProtocolTypeRouter` (using graphene standard graphiql, not the one modified which is provided in the example).

But everything works fine when you're using a client with a correctly configured web socket connection (if you're using this protocol in your `ProtocolTypeRouter`), and it seems it's what the modified graphiql in the example does.

In my case I used `SubscriptionClient` and `addGraphQLSubscriptions` from `subscriptions-transport-ws` in a react application

**Comment by hozblok** [comment]
Hey @Thibaut-Fatus , thank you, we will try to reproduce to add the validation.

**Comment by rigelk** [comment]
Sorry for not answering sooner!

I can confirm my issue occured in the same conditions as @Thibaut-Fatus. It is an easy mistake since the first thing one tends to do to test this library is use the graphiql of their already configured django-graphene endpoint.

**Comment by raulhinojosa** [comment]
@Thibaut-Fatus would you mind sharing a bit how you implemented this in a react app
