### ISSUE TITLE
asyncio.exceptions.CancelledError when connecting

### ISSUE THREAD

**Issue by cellofellow** [datadvance/DjangoChannelsGraphqlWs#28]
I'm just trying to get DjangoChannelsGraphqlWs up and running, but whenever I connect to the websocket with `wscat` I just get a `CancelledError` exception.

```
WebSocket HANDSHAKING /ws/graphql/ [172.19.0.1:56906]
Exception in callback AsyncioSelectorReactor.callLater.<locals>.run() at /usr/local/lib/python3.8/site-packages/twisted/internet/asyncioreactor.py:287
handle: <TimerHandle when=312902.170321491 AsyncioSelectorReactor.callLater.<locals>.run() at /usr/local/lib/python3.8/site-packages/twisted/internet/asyncioreactor.py:287>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.8/site-packages/twisted/internet/asyncioreactor.py", line 290, in run
    f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/daphne/server.py", line 270, in application_checker
    exception = application_instance.exception()
asyncio.exceptions.CancelledError
WebSocket DISCONNECT /ws/graphql/ [172.19.0.1:56906]
```

I haven't tried any other WebSocket clients but I also have a simple Echo consumer at `/ws/echo/` which works fine.

Additionally I'm getting a similar error in my tests.

```
git test -k channels                      
=============================================================== test session starts ===============================================================
platform linux -- Python 3.8.0, pytest-5.2.1, py-1.8.0, pluggy-0.13.0
Django settings: corso.settings (from environment variable)
rootdir: /app
plugins: mock-1.11.1, django-3.6.0, asyncio-0.10.0
collected 55 items / 54 deselected / 1 selected                                                                                                   

knowledge_tree/tests/test_channels/test_topic_tree_subscriptions.py F                                                                       [100%]

==================================================================== FAILURES =====================================================================
____________________________________________________________ test_basic_graphql_query _____________________________________________________________

pyfuncitem = <Function test_basic_graphql_query>

    @pytest.mark.tryfirst
    def pytest_pyfunc_call(pyfuncitem):
        """
        Run asyncio marked test functions in an event loop instead of a normal
        function call.
        """
        for marker_name, fixture_name in _markers_2_fixtures.items():
            if marker_name in pyfuncitem.keywords \
                    and not getattr(pyfuncitem.obj, 'is_hypothesis_test', False):
                event_loop = pyfuncitem.funcargs[fixture_name]
    
                funcargs = pyfuncitem.funcargs
                testargs = {arg: funcargs[arg]
                            for arg in pyfuncitem._fixtureinfo.argnames}
    
>               event_loop.run_until_complete(
                    asyncio.ensure_future(
                        pyfuncitem.obj(**testargs), loop=event_loop))

/usr/local/lib/python3.8/site-packages/pytest_asyncio/plugin.py:156: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <_UnixSelectorEventLoop running=False closed=False debug=False>
future = <Task cancelled name='Task-1' coro=<test_basic_graphql_query() done, defined at /app/knowledge_tree/tests/test_channels/test_topic_tree_subscriptions.py:23>>

    def run_until_complete(self, future):
        """Run until the Future is done.
    
        If the argument is a coroutine, it is wrapped in a Task.
    
        WARNING: It would be disastrous to call run_until_complete()
        with the same coroutine twice -- it would wrap it in two
        different Tasks and that can't be good.
    
        Return the Future's result, or raise its exception.
        """
        self._check_closed()
    
        new_task = not futures.isfuture(future)
        future = tasks.ensure_future(future, loop=self)
        if new_task:
            # An exception is raised if the future didn't complete, so there
            # is no need to log the "destroy pending task" message
            future._log_destroy_pending = False
    
        future.add_done_callback(_run_until_complete_cb)
        try:
            self.run_forever()
        except:
            if new_task and future.done() and not future.cancelled():
                # The coroutine raised a BaseException. Consume the exception
                # to not log a warning, the caller doesn't have access to the
                # local task.
                future.exception()
            raise
        finally:
            future.remove_done_callback(_run_until_complete_cb)
        if not future.done():
            raise RuntimeError('Event loop stopped before Future completed.')
    
>       return future.result()
E       asyncio.exceptions.CancelledError

/usr/local/lib/python3.8/asyncio/base_events.py:608: CancelledError
================================================================ warnings summary =================================================================
/usr/local/lib/python3.8/site-packages/aiohttp/helpers.py:107
  /usr/local/lib/python3.8/site-packages/aiohttp/helpers.py:107: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def noop(*args, **kwargs):  # type: ignore

-- Docs: https://docs.pytest.org/en/latest/warnings.html
================================================== 1 failed, 54 deselected, 1 warnings in 2.57s ==================================================
```

### Relevant files:

My test is pretty simple:

```python
"""Tests for subscriptions to Topic tree changes."""

import channels_graphql_ws.testing
import pytest
from boltons.iterutils import get_path

from corso.routing import application


@pytest.fixture
def wsclient(db, request):
    """Make GraphQL testing client."""  # noqa: D202

    def constructor():
        transport = channels_graphql_ws.testing.GraphqlWsTransport(
            application=application, path="ws/graphql/"
        )
        return channels_graphql_ws.testing.GraphqlWsClient(transport)

    yield constructor


@pytest.mark.asyncio
async def test_basic_graphql_query(wsclient):
    """Test raw connection to GraphqlWsConsumer."""
    client = wsclient()
    await client.connect_and_init()
    response = await client.execute("query { ping }")
    pong = get_path(response, ["data", "ping"])
    assert pong == "pong"
    await client.finalize()
```

`settings.py` relevant bits
```python
...
ASGI_APPLICATION = "corso.routing.application"
...
# Channels
CHANNEL_LAYERS = dict(default=dict(BACKEND="channels.layers.InMemoryChannelLayer"))
```

`corso/schema.py` has my Graphene schema and Consumer classes
```python
"""GraphQL API aggregator."""

import channels
import channels_graphql_ws
import graphene

import knowledge_tree.mutations
import knowledge_tree.schema
import knowledge_tree.subscriptions


class Query(knowledge_tree.schema.Query, graphene.ObjectType):
    """
    Queries from multiple apps.

    - Knowledge Tree
    """


class Mutation(knowledge_tree.mutations.Mutation, graphene.ObjectType):
    """
    Mutations from multiple apps.

    - Knowledge Tree
    """


class Subscription(knowledge_tree.subscriptions.Subscription, graphene.ObjectType):
    """
    Subscriptions from multiple apps.

    - Knowledge Tree
    """


schema = graphene.Schema(query=Query, mutation=Mutation, subscription=Subscription)


class GraphqlWsConsumer(channels_graphql_ws.GraphqlWsConsumer):
    """Channels WebSocket consumer which provides GraphQL API."""

    async def on_connect(self, payload):
        """Handle new websocket connection."""
        """
        Use auxiliary Channels function `get_user` to replace an instance of
        `channels.auth.UserLazyObject` with a native Django user object (user model
        instance or `AnonymousUser`) It is not necessary, but it helps to keep resolver
        code simpler. Cause in both HTTP/WebSocket requests they can use
        `info.context.user`, but not a wrapper. For example objects of type Graphene
        Django type `DjangoObjectType` does not accept `channels.auth.UserLazyObject`
        instances.

        https://github.com/datadvance/DjangoChannelsGraphqlWs/issues/23
        """
        self.scope["user"] = await channels.auth.get_user(self.scope)

    schema = schema
    # strict_ordering = True
    send_keepalive_every = 11
```

`corso/routing.py` has my ASGI application

```python
"""Channels routing for corso project."""

from channels.auth import AuthMiddlewareStack
from channels.generic.websocket import WebsocketConsumer
from channels.routing import ProtocolTypeRouter, URLRouter
from django.urls import path

import corso.schema


class EchoConsumer(WebsocketConsumer):
    """Just echo back all messages."""

    def connect(self):
        """Accept all connections."""
        self.accept()

    def disconnect(self):
        """Do nothing."""

    def receive(self, text_data: str):
        """Echo back data."""
        self.send(text_data=text_data)


application = ProtocolTypeRouter(
    dict(
        websocket=AuthMiddlewareStack(
            # https://channels.readthedocs.io/en/latest/topics/authentication.html
            URLRouter(
                [
                    path("ws/graphql/", corso.schema.GraphqlWsConsumer),
                    path("ws/echo/", EchoConsumer),
                ]
            )
        )
    )
)
```

Haven't gotten to the point of calling any of my subscriptions, so that's a bit offtopic for now.

The "ping" I'm testing looks like this:

```python
class Query:
    """Knowledge Tree GraphQL query root.""

    ...
    ping = graphene.Field(graphene.String)

    def resolve_ping(self, info, **kwargs):
        """Return a pong."""
        return "pong"

    ...
```

**Comment by pitrk** [comment]
I had the same error while working with Django Channels under Python 3.8.0 in docker container, but it usually occurred some time after the connection had already been established. Going back to 3.7 image solved the problem, I also didn't observe this error yet after pulling newer 3.8 image.

**Comment by cellofellow** [comment]
Well, that worked! Strange. Thanks for the reply!

**Comment by Genarito** [comment]
Is there any update on this?

**Comment by Genarito** [comment]
Like @pitrk I'm using Django Channel and Redis with Docker. I've solved the problem updating my Redis server and dependencies. My final versions are:

- Python: 3.8.5 or 3.8.6 (both tested)
- Redis 6.0.8
- Dependencies:

```
channels==2.4.0
channels-redis==3.1.0
daphne==2.5.0
Django==3.1.2
django-filter==2.4.0
djangorestframework==3.12.1
```
Hope it helps

**Comment by michal-michalak** [comment]
Had the same problem on python `3.8.2`. After updating to `3.8.6` it works well.
