### ISSUE TITLE
Subscription Returns Error

### ISSUE THREAD

**Issue by morinx** [datadvance/DjangoChannelsGraphqlWs#32]
Thank you for this package and the comprehensive documentation. Really appreciate it.

I'm getting the following error when trying to run my subscription query:

```py
An error occurred while resolving field Subscription.onNewComment
Traceback (most recent call last):
  File "/Users/noroozim/.pyenv/versions/nexus37/lib/python3.7/site-packages/graphql/execution/executor.py", line 450, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/Users/noroozim/.pyenv/versions/nexus37/lib/python3.7/site-packages/graphql/execution/executors/sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "/Users/noroozim/.pyenv/versions/nexus37/lib/python3.7/site-packages/channels_graphql_ws/subscription.py", line 371, in _subscribe
    register_subscription = root.register_subscription
AttributeError: 'NoneType' object has no attribute 'register_subscription'
```

Here is what I have in my setup:

```py

# /subscription.py/

class OnNewComment(channels_graphql_ws.Subscription):

    comment = Field(types.UserCommentNode)

    class Arguments:
        content_type = String(required=False)

    def subscribe(root, info, content_type):
        return [content_type] if content_type is not None else None

    def publish(self, info, content_type=None):
        new_comment_content_type = self["content_type"]
        new_comment = self["comment"]
        return OnNewComment(
            content_type=content_type, comment=new_comment
        )

    @classmethod
    def new_comment(cls, content_type, comment):
        cls.broadcast(
            # group=content_type,
            payload={"comment": comment},
        )

```

I'm not sure if this is a bug or if I'm missing something.

**Comment by morinx** [comment]
This is where the root is missing:

https://github.com/datadvance/DjangoChannelsGraphqlWs/blob/79d2370ac8ce6dd924b57e312fa92791153dd12a/channels_graphql_ws/subscription.py#L362-L373

**Comment by morinx** [comment]
Found out that I was using the standard `graphiql.html` and had to modify it with the one in the example.
