### ISSUE TITLE
Installation instructions produces TypeError: 'URLPattern' object does not support indexing

### ISSUE THREAD

**Issue by realce2** [datadvance/DjangoChannelsGraphqlWs#54]
```

Starting ASGI/Channels version 2.4.0 development server at http://0:9000/
Quit the server with CONTROL-C.
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/utils/autoreload.py", line 53, in w
er
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/channels/management/commands/runserver.py"
ne 101, in inner_run
    application=self.get_application(options),
  File "/usr/local/lib/python3.6/dist-packages/channels/management/commands/runserver.py"
ne 126, in get_application
    return StaticFilesWrapper(get_default_application())
  File "/usr/local/lib/python3.6/dist-packages/channels/routing.py", line 29, in get_defa
application
    module = importlib.import_module(path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/CURRENT/Master/asgi.py", line 21, in <module>
    django.urls.path('graphql/', MyGraphqlWsConsumer),
  File "/usr/local/lib/python3.6/dist-packages/channels/routing.py", line 105, in __init_
    if self.routes and hasattr(self.routes[0], "pattern"):
TypeError: 'URLPattern' object does not support indexing

```

I have no idea where this trip is occuring or why, I'm using the configs in the installation instructions.

**Comment by prokher** [comment]
@realce2 I don't have any ideas what does this issue is about. It looks like some misconfiguration of the Django routing, but I am not sure. I would recommend starting with an example provided in this repository (which definitely works) and then compare its configuration with the one you have.

Closing this, since currently it does not look like an issue in the `DjangoChannelsGraphqlWs`, but more looks like some misconfiguration of the Django project routing. Feel free to reopen when/if you have more specific information about the issue, especially if this information will point to some flaw in the `DjangoChannelsGraphqlWs` package.
