### ISSUE TITLE
Help: TypeError: __call__() missing 2 required positional arguments: 'receive' and 'send'

### ISSUE THREAD

**Issue by asencis** [datadvance/DjangoChannelsGraphqlWs#56]
Hi there,

I'm seeing the following error when utilizing this library with a Hypercorn server.

On project startup, I am seeing this error:

```
TypeError: __call__() missing 2 required positional arguments: 'receive' and 'send'
```

I can't see exactly why this error is occurring, or what I have done wrong in my config setup...

```
return self.application_mapping[scope["type"]](scope)
web_1      | TypeError: __call__() missing 2 required positional arguments: 'receive' and 'send'
```

Relevant `requirements.txt` details:

```
channels==2.4.0
Django==3.1.4
django-channels-graphql-ws==0.7.5
Hypercorn==0.11.1
websockets==8.1
```

**Comment by prokher** [comment]
@asencis The information you've provided is not enough to help you. Please provide at least stack trace of the `TypeError` you mentioned or better the whole failing example. BTW, does Hypercorn support ASGI?

**Comment by avery-laird** [comment]
I'm having the same issue, with daphne and not hypercorn. Here's the trace I get:

```
Performing system checks...

System check identified no issues (0 silenced).
December 20, 2020 - 18:01:47
Django version 3.1.4, using settings 'server.settings'
Starting ASGI/Channels version 2.4.0 development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Traceback (most recent call last):
  File "</path/to/venv>/virtualenvs/server/lib/python3.9/site-packages/daphne/http_protocol.py", line 163, in process
    self.application_queue = yield maybeDeferred(
TypeError: __call__() missing 2 required positional arguments: 'receive' and 'send'

HTTP GET /graphql 500 [0.00, 127.0.0.1:41684]
Traceback (most recent call last):
  File "</path/to/venv>/virtualenvs/server/lib/python3.9/site-packages/daphne/http_protocol.py", line 163, in process
    self.application_queue = yield maybeDeferred(
TypeError: __call__() missing 2 required positional arguments: 'receive' and 'send'

HTTP GET /favicon.ico 500 [0.00, 127.0.0.1:41684]
```
And the associated configuration:
```python
# asgi.py
import os

from channels.routing import ProtocolTypeRouter, URLRouter
from django.core.asgi import get_asgi_application
from .topowebsocket import TopoWebSocketConsumer
from django.urls import path

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'server.settings')


application = ProtocolTypeRouter({
    'http': get_asgi_application(),
    'websocket': URLRouter([
        path('graphql/', TopoWebSocketConsumer)
    ])
})
```
```python
# topowebsocket.py
import channels_graphql_ws
from .schema import schema


class TopoWebSocketConsumer(channels_graphql_ws.GraphqlWsConsumer):
    schema = schema

    async def on_connect(self, payload):
        print("Client connect!")
```
I can provide additional info if that would help. Thanks for any insight!

**Comment by avery-laird** [comment]
Update: this seems to be an issue with the required version of channels for this package. I forced an update to channels 3, and things seem to be working.

**Comment by Luferov** [comment]
Delete  'http': get_asgi_application() from asgi application in channels ^2, in channels 3 need it.

**Comment by Luferov** [comment]
https://github.com/devind-team/DjangoChannelsGraphqlWs must work correctly.

**Comment by prokher** [comment]
I suppose with an update to Channels 3 in v0.8.0 this should be addressed. Closing this. Feel free to reopen if the issue persists.
