### ISSUE TITLE
Add support for RxPY v3.x

### ISSUE THREAD

**Issue by polofgrs** [datadvance/DjangoChannelsGraphqlWs#90]
Hi,

I am running an app that requires Rx>=3.0.1.  
Running `django-channels-graphql-ws` with RxPy v3.x fails when using GraphQL Subscribe.

## To reproduce
```
pip install Rx==3.2.0
```

Then run the example queries in `readme.md`:  
The first ones (`query` and `mutation`) work alright.

The Subscription:
```GraphQL
subscription s {
  onNewChatMessage(chatroom: "kittens") {
    text
    sender
  }
}
```
Throws:
```json
{
  "data": null,
  "errors": [
    {
      "message": "AttributeError: module 'rx' has no attribute 'subjects'"
    }
  ]
}
```
Full log:
```
Demo middleware report
    operation : subscription
    name      : s
An error occurred while resolving field Subscription.onNewChatMessage
Traceback (most recent call last):
  File "C:\Users\paulf\AppData\Local\Programs\Python\Python38\lib\site-packages\graphql\execution\executor.py", line 452, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "C:\Users\paulf\AppData\Local\Programs\Python\Python38\lib\site-packages\graphql\execution\executors\asyncio.py", line 74, in execute
    result = fn(*args, **kwargs)
  File "C:\Users\paulf\Documents\code\DjangoChannelsGraphqlWs\example\example.py", line 248, in demo_middleware
    return next_middleware(root, info, *args, **kwds)
  File "C:\Users\paulf\AppData\Local\Programs\Python\Python38\lib\site-packages\channels_graphql_ws\graphql_ws_consumer.py", line 596, in register_middleware
    return next_middleware(root, info, *args, **kwds)
  File "C:\Users\paulf\AppData\Local\Programs\Python\Python38\lib\site-packages\channels_graphql_ws\subscription.py", line 434, in _subscribe
    return register_subscription(
  File "C:\Users\paulf\AppData\Local\Programs\Python\Python38\lib\site-packages\asgiref\sync.py", line 204, in __call__
    return call_result.result()
  File "C:\Users\paulf\AppData\Local\Programs\Python\Python38\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()
  File "C:\Users\paulf\AppData\Local\Programs\Python\Python38\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
  File "C:\Users\paulf\AppData\Local\Programs\Python\Python38\lib\site-packages\asgiref\sync.py", line 270, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "C:\Users\paulf\AppData\Local\Programs\Python\Python38\lib\site-packages\channels_graphql_ws\graphql_ws_consumer.py", line 715, in _register_subscription
    trigger = rx.subjects.Subject()
AttributeError: module 'rx' has no attribute 'subjects'
GraphQL resolver failed on operation with id=4:
Traceback (most recent call last):
  File "C:\Users\paulf\AppData\Local\Programs\Python\Python38\lib\site-packages\promise\promise.py", line 87, in try_catch
    return (handler(*args, **kwargs), None)
  File "C:\Users\paulf\AppData\Local\Programs\Python\Python38\lib\site-packages\graphql\execution\executor.py", line 127, in promise_executor
    return execute_operation(exe_context, exe_context.operation, root_value)
  File "C:\Users\paulf\AppData\Local\Programs\Python\Python38\lib\site-packages\graphql\execution\executor.py", line 180, in execute_operation
    return subscribe_fields(exe_context, type, root_value, fields)
  File "C:\Users\paulf\AppData\Local\Programs\Python\Python38\lib\site-packages\graphql\execution\executor.py", line 297, in subscribe_fields
    result = subscribe_field(
  File "C:\Users\paulf\AppData\Local\Programs\Python\Python38\lib\site-packages\graphql\execution\executor.py", line 422, in subscribe_field
    raise result
  File "C:\Users\paulf\AppData\Local\Programs\Python\Python38\lib\site-packages\graphql\execution\executor.py", line 452, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "C:\Users\paulf\AppData\Local\Programs\Python\Python38\lib\site-packages\graphql\execution\executors\asyncio.py", line 74, in execute
    result = fn(*args, **kwargs)
  File "C:\Users\paulf\Documents\code\DjangoChannelsGraphqlWs\example\example.py", line 248, in demo_middleware
    return next_middleware(root, info, *args, **kwds)
  File "C:\Users\paulf\AppData\Local\Programs\Python\Python38\lib\site-packages\channels_graphql_ws\graphql_ws_consumer.py", line 596, in register_middleware
    return next_middleware(root, info, *args, **kwds)
  File "C:\Users\paulf\AppData\Local\Programs\Python\Python38\lib\site-packages\channels_graphql_ws\subscription.py", line 434, in _subscribe
    return register_subscription(
  File "C:\Users\paulf\AppData\Local\Programs\Python\Python38\lib\site-packages\asgiref\sync.py", line 204, in __call__
    return call_result.result()
  File "C:\Users\paulf\AppData\Local\Programs\Python\Python38\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()
  File "C:\Users\paulf\AppData\Local\Programs\Python\Python38\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
  File "C:\Users\paulf\AppData\Local\Programs\Python\Python38\lib\site-packages\asgiref\sync.py", line 270, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "C:\Users\paulf\AppData\Local\Programs\Python\Python38\lib\site-packages\channels_graphql_ws\graphql_ws_consumer.py", line 715, in _register_subscription
    trigger = rx.subjects.Subject()
AttributeError: module 'rx' has no attribute 'subjects'
```

Is there any way to provide support for [RxPY v3.x](https://pypi.org/project/Rx/)?

Thank you!

**Comment by prokher** [comment]
The version 1.0.0rc1 is available in PyPI, it supports latest Django & Graphene, and does not have RxPy as dependency anymore. Closing this.
